### ISSUE TITLE
crash on load up(teslathingies-1.11.2-0.0.2)

### ISSUE THREAD

**Issue by SDUBZ** [faceofcat/Tesla-Powered-Thingies#1]
tesla core: Tesla-1.11-1.3.0.51
tesla powerwed thingies: teslathingies-1.11.2-0.0.2
tesla core lib: tesla-core-lib-1.11.2-0.6.0
mek farm: mekfarm-1.11.2-0.6.0
forge:1.11.2-2282

crash report:
[crash-2017-04-13_11.03.21-client.txt](https://github.com/faceofcat/Tesla-Powered-Thingies/files/918251/crash-2017-04-13_11.03.21-client.txt)

**Comment by faceofcat** [comment]
Tesla Core Lib : 1.11.2 - 0.6.1
that fixes the issue.
