### ISSUE TITLE
When machines are set to be active on a redstone signal, they stop working.

### ISSUE THREAD

**Issue by LocoMinerDad** [faceofcat/Tesla-Powered-Thingies#15]
Hi there,
Great Mod BTW. I thought of a third issue
Issue 1: embers mod ores won't go into your machines except the kiln. 
issue 2: when your machines are set to active on a redstone signal. They stop working. I have tried it with a lever on the machines and the block next to it in both on and off positions. They only work on always active or ignore redstone signal.
Issue 3: the incinerator can charge items but only if feed coal etc. it can't accept power from a reactor or other outside source.
Mod version HF3, minecraft 12

thank you

**Comment by faceofcat** [comment]
1. "embers mod ores"... probably not oredict-ed correctly... or ore dict is done at the wrong time... I will investigate this when I get a chance.

2. hmm... that's bad!

3. yes... that's not a bug... the "charger" part is only for the generator itself... could make a "charger" block I guess... but that's not a priority.

**Comment by faceofcat** [comment]
1 - got a new task: #16

3 - not a bug... ignoring for now.

so this issue is only about 2 :)
