### ISSUE TITLE
[1.12.2] Powered Pump consumes Fluids

### ISSUE THREAD

**Issue by accessdenied0** [faceofcat/Tesla-Powered-Thingies#36]
I wasn't sure if this is an issue or not. Maybe it is intentional but: If you're not quick enough, the Powered Pump consumes the Fluid if the internal buffer is full. It keeps pumping and "destroying" Fluid-blocks even if the internal tank is full.

**Comment by faceofcat** [comment]
fixed in 7eea0c1065ab1ae3319c0f376b2594c3ebe7ee71
