### ISSUE TITLE
Butcher has no drops

### ISSUE THREAD

**Issue by AniMaid** [faceofcat/Tesla-Powered-Thingies#39]
When the electric butcher kills animals, it neither leaves drops in world nor places them in it's inventory.
Version 1.0.12 for minecraft 1.12.2

**Comment by faceofcat** [comment]
what kind of animals?... vanilla?... or from some mod?

**Comment by AniMaid** [comment]
I've tried both pigs and cows.

It's also not a mod interaction, it was doing this with just JEI, HWYLA, More Overlays, and this mod and it's dependencies, with forge version 2555. And exp orbs drop, but not any meat/leather/etc.
