### ISSUE TITLE
(enhancement) Configs

### ISSUE THREAD

**Issue by FoxBotGames** [faceofcat/Tesla-Powered-Thingies#45]
More configs pls
There are config files that have one or two configs where several machines are still missing Config files.
Missing: AnimalFarm, AnimalGym, AnimalReleaser, CropCloner, CropFarm, ElectricButcher, FluidSolidifier, LiquidXPStorage, FarmerMachine, PoweredPump, and Sewer.

**Comment by faceofcat** [comment]
well... yeah... but the specific config files are usually for custom recipes...

the rest of the machines don't have any kind of recipes... so not sure what would be in those configs.

**Comment by FoxBotGames** [comment]
Good point....
