### ISSUE TITLE
crop farm

### ISSUE THREAD

**Issue by LocoMinerDad** [faceofcat/Tesla-Powered-Thingies#6]
how do you use it. it has power, water and wheat, carrot seeds but nothing is happening?

**Comment by faceofcat** [comment]
does it have a hoe?... or is the land already tilled?

water is also optional if the land is naturally wet.

**Comment by LocoMinerDad** [comment]
It doesnt gave a hoe. Do you have a guide somewhere that tells us what your machines need to operate? Does it work with mod plants?


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: faceofcat <notifications@github.com> Date: 9/10/17  8:32 PM  (GMT-08:00) To: faceofcat/Tesla-Powered-Thingies <Tesla-Powered-Thingies@noreply.github.com> Cc: LocoMinerDad <richard_swingle@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [faceofcat/Tesla-Powered-Thingies] crop farm (#6) 
does it have a hoe?... or is the land already tilled?
water is also optional if the land is naturally wet.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/faceofcat/Tesla-Powered-Thingies","title":"faceofcat/Tesla-Powered-Thingies","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/faceofcat/Tesla-Powered-Thingies"}},"updates":{"snippets":[{"icon":"PERSON","message":"@faceofcat in #6: does it have a hoe?... or is the land already tilled?\r\n\r\nwater is also optional if the land is naturally wet."}],"action":{"name":"View Issue","url":"https://github.com/faceofcat/Tesla-Powered-Thingies/issues/6#issuecomment-328406743"}}}

**Comment by faceofcat** [comment]
not yet... :(

but... it's pretty straight forward:
1. provide it with power (Tesla, Forge Energy, RF, Mekanism, MJ)
2. either provide it with a hoe, or till the land yourself (you can use the 'show working area' thing to see where it will look for plants)
3. either provide it with water, or make sure the land is naturally moisturized (from nearby water blocks)
4. either provide it with seeds, or plant the initial plants yourself)
5. (optional) provide it with bonemeal

that should be it...

**Comment by LocoMinerDad** [comment]
all good thx
